### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by dhrrgn** [php-fig/event-dispatcher-util#11]
Can a new release get tagged and published to Packagist?  I would like to use invokables, but can't until #9 is released.

Thanks!

**Comment by Jean85** [comment]
Ping @Crell, can you take care of this?

**Comment by WyriHaximus** [comment]
@Jean85 / @Crell Would a `1.0.1` do or should we tag `1.1.0`?

**Comment by Jean85** [comment]
Since there's a new feature I would say 1.1

**Comment by WyriHaximus** [comment]
@Jean85 oki will tag 1.1 momentarily

**Comment by WyriHaximus** [comment]
Just tagged [`1.1.0`](https://github.com/php-fig/event-dispatcher-util/releases/tag/1.1.0).
