### ISSUE TITLE
Type callable for getParameterType() in ParameterDeriverTrait

### ISSUE THREAD

**Issue by hermann8u** [php-fig/event-dispatcher-util#12]
Hi,

For the ParameterDeriverTrait::getParameterType method there is no declared type for the argument $callable.
https://github.com/php-fig/event-dispatcher-util/blob/29725c77467dddf637d08579e63b28a14209dbff/src/ParameterDeriverTrait.php#L19
There is a comment below explaining why but I'm not sure it's correct.
https://github.com/php-fig/event-dispatcher-util/blob/29725c77467dddf637d08579e63b28a14209dbff/src/ParameterDeriverTrait.php#L21

I have updated the trait locally in order to add the type *callable* and I tried the code below and it works well :

``` php
$listenerProvider = new RandomListenerProviderUsingTheTrait();

class CallableHolder
{
    public function onStdEvent(\stdClass $event)
    {
    }
}

$callabelHolder = new CallableHolder();

var_dump($listenerProvider->getParameterType([$callabelHolder, 'onStdEvent']));
```

Am I missing something?

Thank you!

**Comment by Crell** [comment]
See the comment on `isClassCallable`.  The code nominally supports `['ClassName', 'methodName']` for an *instance* of `ClassName`, whereas AFAIK that only qualifies as a valid callable-array in PHP if `methodName` is static.

Although, when I add the type hint locally and run the tests, they pass, despite having a test for a class/method that isn't yet instantiated.  Hm.  I wonder if that changed in some PHP version at some point?  I'm on 7.4 right now, but the code was written on 7.2 originally...  Anyone have a 7.2 system lying around to test on? :smile:

**Comment by Crell** [comment]
Ah, here we go.  It's if the class in question is not defined at the time of the call, but would be defined later.  cf: https://3v4l.org/BYiL2

I know I ran into that at some point during development of that routine, but I don't recall precisely what circumstances it was.  It's *possible* we could add the type hint, but I'm wary of discovering whatever that edge case was again, the hard way.

**Comment by Crell** [comment]
Improved the comment in #17 to explain why we can't type that param.

**Comment by hermann8u** [comment]
Nice job ! :)
